---
- name: Update and Upgrade all packages on Ubuntu/Debian systems
  hosts: all
  become: yes  
  tasks:
    - name: Ensure the system is updated
      apt:
        update_cache: yes
        cache_valid_time: 3600  

    - name: Upgrade all packages to the latest version
      apt:
        upgrade: dist
        autoremove: yes  
        autoclean: yes  
